<?php

/**
 * @copyright   Copyright (C) 2010-2026 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

//
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'sample-portal-dev-new-brick/1.0.0',
	[
		// Identification
		//
		'label' => 'Sample to show which files are necessary to create a new brick for the portal',
		'category' => 'portal',

		// Setup
		//
		'dependencies' => [
			'itop-portal-base/3.3.0',
		],
		'mandatory' => false,
		'visible' => true,

		// Components
		//
		'datamodel' => [
			'vendor/autoload.php',
			'model.sample-portal-dev-new-brick.php', // Contains the PHP code generated by the "compilation" of datamodel.sample-portal-dev-new-brick.xml
			'src/Router/imagebrickrouter.inc.php',
		],
		'webservice' => [],
		'data.struct' => [
			// add your 'structure' definition XML files here,
		],
		'data.sample' => [
			// add your sample data XML files here,
		],

		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any

		// Default settings
		//
		'settings' => [
			// Module specific settings go here, if any
		],
	]
);
